kumuluzee:
  name: delivery-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/DeliveryMetadataDS
      connection-url: jdbc:postgresql://localhost:5432/delivery-metadata
      username: dbuser
      password: postgres
      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/DeliveryMetadataDS
    metrics:
        web-instrumentation:
          - name: deliveries-endpoint
            url-pattern: /v1/deliveries/*

rest-properties:
  maintenance-mode: false
  broken: false

  #kumuluzee.name
  #KUMULUEE_NAME

  #kumuluzee.env.name
  #KUMULUZEE_ENV_NAME

  #kumuluzee.datasources[0].connection-url
  #KUMULZEE_DATASOURCES0_CONNECTIONURL